---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  # renovate: datasource=docker depName=ghcr.io/dragonflydb/dragonfly repository=ghcr.io
  image: ghcr.io/dragonflydb/dragonfly:v1.33.1
  replicas: 3
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
    - name: DRAGONFLY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dragonfly-secret
          key: DRAGONFLY_PASSWORD
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
    - --cluster_mode=emulated
    - --lock_on_hashtags
    - --requirepass=$(DRAGONFLY_PASSWORD)
    - --default_lua_flags=allow-undeclared-keys
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: "DoNotSchedule"
      labelSelector:
        matchLabels:
          app.kubernetes.io/part-of: dragonfly
