---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dragonfly
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dragonfly-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DRAGONFLY_PASSWORD: "{{ .DRAGONFLY_PASSWORD }}"
  dataFrom:
    - extract:
        key: dragonfly
