---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: "1h"
  target:
    name: netbox-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .NETBOX_SECRET_KEY }}"
        SUPERUSER_EMAIL: "{{ .NETBOX_SUPERUSER_EMAIL }}"
        SUPERUSER_NAME: "{{ .NETBOX_SUPERUSER_NAME }}"
        SUPERUSER_PASSWORD: "{{ .NETBOX_SUPERUSER_PASSWORD }}"
        SUPERUSER_API_TOKEN: "{{ .NETBOX_SUPERUSER_API_TOKEN }}"
        DB_PASSWORD: "{{ .NETBOX_POSTGRESQL_PASSWORD }}"
        DB_HOST: "cnpg-netbox-rw.default.svc.cluster.local"
        DB_PORT: "5432"
        DB_NAME: "netboxdb"
        DB_USER: "netboxusr"
        DATABASE_URL: "postgres://netboxusr:{{ .NETBOX_POSTGRESQL_PASSWORD }}@cnpg-netbox-rw.default.svc.cluster.local:5432/netboxdb"
  dataFrom:
    - extract:
        key: netbox
