---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-open-webui-backup-weekly
spec:
  schedule: "0 2 * * 1"  # Every Monday at 2 AM
  immediate: false
  backupOwnerReference: self
  cluster:
    name: cnpg-open-webui
