---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .PAPERLESS_DBUSER }}"
        password: "{{ .PAPERLESS_DBPASS }}"
        ACCESS_KEY_ID: "{{ .S3_KEY_ID}}"
        SECRET_ACCESS_KEY: "{{ .S3_KEY_SECRET }}"
  dataFrom:
    - extract:
        key: paperless
    - extract:
        key: cloudflare
