---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: 7.0.0
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    image:
      flavor: fpm-alpine
    nginx:
      enabled: true
      image:
        repository: nginxinc/nginx-unprivileged
        tag: 1.29-alpine-perl
        pullPolicy: IfNotPresent
      securityContext:
        runAsUser: 3000
        runAsGroup: 3000
        fsGroup: 3000
        runAsNonRoot: false
    nextcloud:
      datadir: /var/www/data
      extraEnv:
        - name: REDIS_HOST
          value: dragonfly.database.svc.cluster.local
        - name: REDIS_HOST_PORT
          value: "6379"
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
      host: &host cloud.${SECRET_DOMAIN}
      mail:
        enabled: true
        fromAddress: admin
        domain: ${SECRET_DOMAIN}
        smtp:
          host: ${SECRET_MAIL_SERVER}
          port: 25
          authtype: NONE
          name: ""
          password: ""
      securityContext:
        runAsUser: 3000
        runAsGroup: 3000
        fsGroup: 3000
        runAsNonRoot: false
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.0.0.0/8',
              2 => '172.16.0.0/12',
              3 => '192.168.0.0/16'
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          ); ?>
        misc.config.php: |-
          <?php
          $CONFIG = array (
            'default_phone_region' => 'DE',
            'maintenance_window_start' => 2,
          ); ?>
      extraSidecarContainers:
        - name: nextcloud-clamav
          image: clamav/clamav:1.4.3@sha256:35b689111f3cfefe6ab00a5fe58dc45a078b267508c0c584a2616775cb160c4b
          env:
            - name: CLAMAV_NO_CLAMD
              value: "false"
            - name: CLAMAV_NO_FRESHCLAMD
              value: "false"
            - name: CLAMAV_NO_MILTERD
              value: "true"
            - name: FRESHCLAM_CHECKS
              value: "4"
          ports:
            - name: http
              containerPort: 3310
              protocol: TCP
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
        - name: languagetool
          image: collabora/languagetool:6.4@sha256:09a095cb078026e832bfa3d8fafaf18656dee00b6fd86e1f2c6a323a107fa697
          ports:
            - name: http
              containerPort: 8010
              protocol: TCP
      #  - name: whiteboard
      #    image: ghcr.io/nextcloud-releases/whiteboard:v1.1.2
      #    env:
      #      - name: NEXTCLOUD_URL
      #        value: "cloud.${SECRET_DOMAIN}"
      #      - name: JWT_SECRET_KEY
      #        valueFrom:
      #          secretKeyRef:
      #            name: nextcloud-secret
      #            key: WHITEBOARD_JWT_SECRET_KEY
      #      - name: STORAGE_STRATEGY
      #        value: "redis"
      #      - name: REDIS_URL
      #        value: "redis://:${DRAGONFLY_PASSWORD}@dragonfly.database.svc.cluster.local:6379/9"
      #    ports:
      #      - name: http
      #        containerPort: 3002
      #        protocol: TCP
      #    securityContext:
      #      runAsUser: 65534
      #      runAsGroup: 65534
      #      fsGroup: 65534
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: cnpg-nextcloud-rw.default.svc.cluster.local
      database: nextclouddb
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: POSTGRES_USER
        passwordKey: POSTGRES_PASSWORD
    collabora:
      enabled: true
      collabora:
        aliasgroups:
          - host: "https://cloud.${SECRET_DOMAIN}"
      extra_params: --o:ssl.enable=false --o:ssl.termination=true --o:welcome.enable=false --o:languagetool.enabled=true --o:languagetool.base_url=http://nextcloud-languagetool.default.svc.cluster.local:8010/v2 --o:admin_console.enable=false
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: COLLABORA_USERNAME
        passwordKey: COLLABORA_PASSWORD
    cronjob:
      enabled: true
    persistence:
      enabled: true
      existingClaim: nextcloud-pvc
    startupProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1
