---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nextcloud-storage
  mountOptions:
    - hard
    - rw
    - nfsvers=4.2
  nfs:
    path: /mnt/hdd/k8s/ncd
    server: ${SECRET_NAS_SERVER}
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nextcloud-storage
  resources:
    requests:
      storage: 200Gi
