---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./backup-6h.yaml
  - ./backup-daily.yaml
  - ./snapshot-1h.yaml
  - ./snapshot-6h.yaml
