---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: longhorn-system-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ENDPOINTS: "{{ .S3_URL }}"
        AWS_ACCESS_KEY_ID: "{{ .S3_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .S3_KEY_SECRET }}"
  dataFrom:
    - extract:
        key: cloudflare
