---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.9.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
      reclaimPolicy: Delete
      recurringJobSelector:
        enable: false
      removeSnapshotsDuringFilesystemTrim: enabled
      dataEngine: v1
    defaultSettings:
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 10
      defaultLonghornStaticStorageClass: longhorn-standard
      restoreVolumeRecurringJobs: true
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      autoCleanupSystemGeneratedSnapshot: true
      autoCleanupRecurringJobBackupSnapshot: true
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      orphanResourceAutoDeletion: replica-data
      snapshotDataIntegrity: enabled
      snapshotDataIntegrityImmediateCheckAfterSnapshotCreation: false
      snapshotDataIntegrityCronjob: "0 4 * * *"
      fastReplicaRebuildEnabled: true
      removeSnapshotsDuringFilesystemTrim: true
      v1DataEngine: true
      v2DataEngine: false
      allowCollectingLonghornUsageMetrics: false
      freezeFilesystemForSnapshot: true
      autoCleanupSnapshotWhenDeleteBackup: true
      autoCleanupSnapshotAfterOnDemandBackupCompleted: true
      rwxVolumeFastFailover: true
    defaultBackupStore:
      backupTarget: s3://k8s-longhorn@us-east-1/
      backupTargetCredentialSecret: longhorn-system-secret
