---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-netbox
spec:
  description: Postgresql cluster for Netbox
  # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql repository=ghcr.io
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6-standard-trixie
  instances: 1
  storage:
    size: 10Gi
    storageClass: longhorn-postgres
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 256MB
 # plugins:
 #   - name: barman-cloud.cloudnative-pg.io
 #     enabled: true
 #     isWALArchiver: true
 #     parameters:
 #       barmanObjectName: netbox-barman-backup
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  primaryUpdateStrategy: unsupervised
  monitoring:
    enablePodMonitor: true
  # Initial bootstrap for first install
  bootstrap:
    initdb:
      database: netboxdb
      owner: netboxusr
      secret:
        name: netbox-db-secret
      encoding: 'UTF8'
