---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: open-webui-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Open WebuUI
        DATABASE_URL: "postgresql://{{ .OPENWEBUI_DBUSER }}:{{ .OPENWEBUI_DBPASS }}@cnpg-open-webui-rw.default.svc.cluster.local:5432/openwebuidbapp?sslmode=disable"
        WEBSOCKET_REDIS_URL: "redis://:${DRAGONFLY_PASSWORD}@dragonfly.database.svc.cluster.local:6379"
        OPENAI_API_KEY: "{{ .OPENROUTER_OPENWEBUI_API_KEY }}"
        OAUTH_CLIENT_ID: "{{ .OPEN_WEBUI_OIDC_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .OPEN_WEBUI_OIDC_CLIENT_SECRET }}"
        WEBUI_SECRET_KEY: "{{ .OPEN_WEBUI_SECRET_KEY }}"
        PGVECTOR_DB_URL: "postgresql://{{ .OPENWEBUI_DBUSER }}:{{ .OPENWEBUI_DBPASS }}@cnpg-open-webui-rw.default.svc.cluster.local:5432/openwebuidbrag?sslmode=disable"
        # Google Search
        GOOGLE_PSE_ENGINE_ID: "{{ .GOOGLE_PSE_ID }}"
        GOOGLE_PSE_API_KEY: "{{ .GOOGLE_PSE_KEY }}"
  dataFrom:
    - extract:
        key: google
    - extract:
        key: openwebui
    - extract:
        key: openrouter
