---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: open-webui-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Open WebuUI
        DATABASE_URL: "postgres://{{ .OPENWEBUI_DBUSER }}:{{ .OPENWEBUI_DBPASS }}@cnpg-openwebui-rw.default.svc.cluster.local:5432/openwebuidb?sslmode=disable"
        WEBSOCKET_REDIS_URL: "redis://:${DRAGONFLY_PASSWORD}@dragonfly.database.svc.cluster.local:6379"
        OPENAI_API_KEY: "{{ .OPENROUTER_OPENWEBUI_API_KEY }}"
        OAUTH_CLIENT_ID: "{{ .OPEN_WEBUI_OIDC_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .OPEN_WEBUI_OIDC_CLIENT_SECRET }}"
        WEBUI_SECRET_KEY: "{{ .OPEN_WEBUI_SECRET_KEY }}"
        # SearxNG
        SEARXNG_SECRET: "{{ .SEARXNG_SECRET }}"
  dataFrom:
    - extract:
        key: searxng
    - extract:
        key: openwebui
    - extract:
        key: openrouter
