---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
          secret.reloader.stakater.com/reload: open-webui-secret
        containers:
          open-webui:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: 0.6.28@sha256:4fe25c664d4d50f98f21594f12b59612bf7f5cabcff8e516c5c8521193d9c498
            env:
              CORS_ALLOW_ORIGIN: https://gpt.${SECRET_DOMAIN}
              WEBUI_URL: https://gpt.${SECRET_DOMAIN}
              PORT: &webuiPort 8090
              ENABLE_SIGNUP: false
              ENABLE_OAUTH_SIGNUP: true
              ENABLE_LOGIN_FORM: false
              DEFAULT_LOCALE: de
              DEFAULT_USER_ROLE: user
              DATA_DIR: /data
              ENV: prod
              ENABLE_OLLAMA_API: false
              OPENAI_API_BASE_URL: https://openrouter.ai/api/v1
              ENABLE_WEB_SEARCH: true
              ENABLE_SEARCH_QUERY_GENERATION: true
              WEB_SEARCH_RESULT_COUNT: 5
              WEB_SEARCH_ENGINE: google_pse
              ENABLE_WEBSOCKET_SUPPORT: "true"
              WEBSOCKET_MANAGER: "redis"
              OAUTH_PROVIDER_NAME: Authentik
              OAUTH_MERGE_ACCOUNTS_BY_EMAIL: false
              OPENID_PROVIDER_URL: https://id.${SECRET_DOMAIN}/application/o/open-webui/.well-known/openid-configuration
              OPENID_REDIRECT_URI: https://gpt.${SECRET_DOMAIN}/oauth/oidc/callback
              OAUTH_SCOPES: openid email profile
              OAUTH_UPDATE_PICTURE_ON_LOGIN: true
              ENABLE_OAUTH_GROUP_MANAGEMENT: true
              OAUTH_GROUP_CLAIM: groups
              ENABLE_OAUTH_GROUP_CREATION: true
              TZ: ${TIMEZONE}
              VECTOR_DB: pgvector
              PGVECTOR_INITIALIZE_MAX_VECTOR_LENGTH: 1536
              CONTENT_EXTRACTION_ENGINE: tika
              TIKA_SERVER_URL: http://paperless-tika.default.svc.cluster.local:9998
              ENABLE_API_KEY: true
              JWT_EXPIRES_IN: 8h
            envFrom:
              - secretRef:
                  name: open-webui-secret
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                memory: 4Gi
            securityContext:
              runAsNonRoot: false
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 0
    service:
      open-webui:
        controller: main
        ports:
          http:
            port: *webuiPort
    route:
      open-webui:
        hostnames:
          - gpt.${SECRET_DOMAIN}
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: open-webui
                port: *webuiPort
    persistence:
      data:
        enabled: true
        existingClaim: open-webui-pvc
        advancedMounts:
          main:
            open-webui:
              - path: /data
                subPath: data
