---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
          secret.reloader.stakater.com/reload: open-webui-secret
        containers:
          open-webui:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: v0.6.15@sha256:fda936056184035a71a9ad5ff3721530ff061f16bc3907efb33a3201ba87ccfe
            env:
              CORS_ALLOW_ORIGIN: https://gpt.${SECRET_DOMAIN}
              WEBUI_URL: https://gpt.${SECRET_DOMAIN}
              ENABLE_SIGNUP: true
              ENABLE_OAUTH_SIGNUP: true
              DEFAULT_LOCALE: de
              DEFAULT_USER_ROLE: user
              DATA_DIR: /data
              ENV: prod
              ENABLE_OLLAMA_API: false
              OPENAI_API_BASE_URL: https://openrouter.ai/api/v1
              ENABLE_RAG_WEB_SEARCH: true
              RAG_WEB_SEARCH_ENGINE: searxng
              SEARXNG_QUERY_URL: http://open-webui-searxng.default.svc.cluster.local:8080/search?q=<query>
              ENABLE_WEBSOCKET_SUPPORT: "true"
              WEBSOCKET_MANAGER: "redis"
              OAUTH_PROVIDER_NAME: Authentik
              OAUTH_MERGE_ACCOUNTS_BY_EMAIL: false
              OPENID_PROVIDER_URL: https://id.${SECRET_DOMAIN}/application/o/open-webui/.well-known/openid-configuration
              OPENID_REDIRECT_URI: https://gpt.${SECRET_DOMAIN}/oauth/oidc/callback
              OAUTH_SCOPES: openid email profile
              OAUTH_UPDATE_PICTURE_ON_LOGIN: false
              TZ: ${TIMEZONE}
              VECTOR_DB: elasticsearch
              ELASTICSEARCH_URL: http://open-webui-elasticsearch.default.svc.cluster.local:9200
              CONTENT_EXTRACTION_ENGINE: tika
              TIKA_SERVER_URL: http://paperless-tika.default.svc.cluster.local:9998
            envFrom:
              - secretRef:
                  name: open-webui-secret
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                memory: 4Gi
            securityContext:
              runAsNonRoot: false
              runAsUser: 3000
              runAsGroup: 3000
              fsGroup: 3000
          elasticsearch:
            image:
              repository: docker.elastic.co/elasticsearch/elasticsearch
              tag: 9.0.3
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 4096Mi
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            env:
              TZ: ${TIMEZONE}
              xpack.security.enabled: "false"
              discovery.type: "single-node"
              ES_JAVA_OPTS: "-Xms512m -Xmx512m"
            securityContext:
              runAsNonRoot: false
              runAsUser: 3000
              runAsGroup: 3000
              fsGroup: 3000
          searxng:
            image:
              repository: ghcr.io/searxng/searxng
              tag: 2025.6.6-33891e5@sha256:64e7df5acb7399caafc457096082ea662639ef8742b5e37015bc1c2a9451ba0d
            command:
              - /usr/local/searxng/venv/bin/uwsgi
              - --master
              - /usr/local/searxng/.template/uwsgi.ini
            env:
              SEARXNG_BASE_URL: http://open-webui-searxng.default.svc.cluster.local
              SEARXNG_URL: http://open-webui-searxng.default.svc.cluster.local:8090
              SEARXNG_PORT: &httpPort 8090
              UWSGI_WORKERS: "1"
            envFrom:
              - secretRef:
                  name: open-webui-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /stats
                    port: *httpPort
                  initialDelaySeconds: 15
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETGID
                  - SETUID
                  - DAC_OVERRIDE
        initContainers:
          init-chmod-pvc:
            image:
              repository: docker.io/library/alpine
              tag: 3.22.0@sha256:8a1f59ffb675680d47db6337b49d22281a139e9d709335b492be023728e11715
            command: ["/bin/sh"]
            args: ["-c", "mkdir -p /usr/share/elasticsearch && chmod 0770 /usr/share/elasticsearch && chown 3000:3000 /usr/share/elasticsearch"]
            securityContext:
              runAsUser: 0
              runAsGroup: 0
    service:
      open-webui:
        controller: main
        ports:
          http:
            port: 8080
      elasticsearch:
        controller: main
        ports:
          http:
            port: 9200
      searxng:
        controller: main
        ports:
          http:
            port: *httpPort
    route:
      open-webui:
        hostnames:
          - gpt.${SECRET_DOMAIN}
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: open-webui
                port: 8080
    persistence:
      data:
        enabled: true
        existingClaim: open-webui-pvc
        advancedMounts:
          main:
            open-webui:
              - path: /data
                subPath: data/open-webui
            elasticsearch:
              - path: /usr/share/elasticsearch
                subPath: data/elasticsearch
            init-chmod-pvc:
              - path: /usr/share/elasticsearch
                subPath: data/elasticsearch
      searxng-config:
        enabled: true
        type: configMap
        name: searxng-configmap
        advancedMounts:
          main:
            searxng:
              - path: /etc/searxng/settings.yml
                subPath: settings.yml
              - path: /etc/searxng/limiter.toml
                subPath: limiter.toml
              - path: /etc/searxng/favicons.toml
                subPath: favicons.toml
      searxng-tmp:
        type: emptyDir
        advancedMounts:
          main:
            searxng:
              - path: /etc/searxng
              - path: /tmp
              - path: /var/cache/searxng/
