---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
          secret.reloader.stakater.com/reload: open-webui-secret
        containers:
          open-webui:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: v0.6.15@sha256:fda936056184035a71a9ad5ff3721530ff061f16bc3907efb33a3201ba87ccfe
            env:
              CORS_ALLOW_ORIGIN: https://gpt.${SECRET_DOMAIN}
              WEBUI_URL: https://gpt.${SECRET_DOMAIN}
              PORT: &webuiPort 8090
              ENABLE_SIGNUP: true
              ENABLE_OAUTH_SIGNUP: true
              DEFAULT_LOCALE: de
              DEFAULT_USER_ROLE: user
              DATA_DIR: /data
              ENV: prod
              ENABLE_OLLAMA_API: false
              OPENAI_API_BASE_URL: https://openrouter.ai/api/v1
              ENABLE_RAG_WEB_SEARCH: true
              RAG_WEB_SEARCH_ENGINE: searxng
              SEARXNG_QUERY_URL: http://open-webui-searxng.default.svc.cluster.local:8080/search?q=<query>
              ENABLE_WEBSOCKET_SUPPORT: "true"
              WEBSOCKET_MANAGER: "redis"
              OAUTH_PROVIDER_NAME: Authentik
              OAUTH_MERGE_ACCOUNTS_BY_EMAIL: false
              OPENID_PROVIDER_URL: https://id.${SECRET_DOMAIN}/application/o/open-webui/.well-known/openid-configuration
              OPENID_REDIRECT_URI: https://gpt.${SECRET_DOMAIN}/oauth/oidc/callback
              OAUTH_SCOPES: openid email profile
              OAUTH_UPDATE_PICTURE_ON_LOGIN: true
              TZ: ${TIMEZONE}
              VECTOR_DB: pgvector
              PGVECTOR_INITIALIZE_MAX_VECTOR_LENGTH: 1536
              CONTENT_EXTRACTION_ENGINE: tika
              TIKA_SERVER_URL: http://paperless-tika.default.svc.cluster.local:9998
            envFrom:
              - secretRef:
                  name: open-webui-secret
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                memory: 4Gi
            securityContext:
              runAsNonRoot: false
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 0
          searxng:
            image:
              repository: ghcr.io/searxng/searxng
              tag: 2025.7.18-ff2e0ea@sha256:c1ad2bd15604fc3c783cf67666371dda8df9f3a078fef1dba67057bf766b8b30
            env:
              SEARXNG_BASE_URL: http://open-webui-searxng.default.svc.cluster.local
              SEARXNG_URL: http://open-webui-searxng.default.svc.cluster.local:8080
              SEARXNG_PORT: &searxngPort 8080
              UWSGI_WORKERS: "1"
            envFrom:
              - secretRef:
                  name: open-webui-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /stats
                    port: *searxngPort
                  initialDelaySeconds: 15
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETGID
                  - SETUID
                  - DAC_OVERRIDE
    service:
      open-webui:
        controller: main
        ports:
          http:
            port: *webuiPort
      searxng:
        controller: main
        ports:
          http:
            port: *searxngPort
    route:
      open-webui:
        hostnames:
          - gpt.${SECRET_DOMAIN}
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: open-webui
                port: *webuiPort
    persistence:
      data:
        enabled: true
        existingClaim: open-webui-pvc
        advancedMounts:
          main:
            open-webui:
              - path: /data
                subPath: data
      searxng-config:
        enabled: true
        type: configMap
        name: searxng-configmap
        advancedMounts:
          main:
            searxng:
              - path: /etc/searxng/settings.yml
                subPath: settings.yml
              - path: /etc/searxng/limiter.toml
                subPath: limiter.toml
              - path: /etc/searxng/favicons.toml
                subPath: favicons.toml
      searxng-tmp:
        type: emptyDir
        advancedMounts:
          main:
            searxng:
              - path: /etc/searxng
              - path: /tmp
              - path: /var/cache/searxng/
