---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
configMapGenerator:
  - name: searxng-configmap
    files:
      - settings.yml=./resources/settings.yaml
      - limiter.toml=./resources/limiter.toml
      - favicons.toml=./resources/favicons.toml
generatorOptions:
  disableNameSuffixHash: true
