---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: "1h"
  target:
    name: paperless-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PAPERLESS_DBENGINE: postgresql
        PAPERLESS_DBPORT: "5432"
        PAPERLESS_DBNAME: "{{ .PAPERLESS_DBNAME }}"
        PAPERLESS_DBHOST: cnpg-paperless-rw.default.svc.cluster.local
        PAPERLESS_DBUSER: "{{ .PAPERLESS_DBUSER }}"
        PAPERLESS_DBPASS: "{{ .PAPERLESS_DBPASS }}"
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_API_TOKEN: "{{ .PAPERLESS_API_TOKEN }}"
        PAPERLESS_USERNAME: "{{ .PAPERLESS_API_USER }}"
        CUSTOM_API_KEY: "{{ .OPENROUTER_PAPERLESSAI_API_KEY }}"
  dataFrom:
    - extract:
        key: paperless
    - extract:
        key: openrouter
