---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-data-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: paperless-data-nfs
  mountOptions:
    - hard
    - rw
    - nfsvers=4.2
  nfs:
    path: /mnt/hdd/k8s/pls
    server: ${SECRET_NAS_SERVER}
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data-pvc
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: paperless-data-nfs
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-consume-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: paperless-consume-nfs
  mountOptions:
    - hard
    - rw
    - nfsvers=4.2
  nfs:
    path: /mnt/hdd/shr/pls
    server: ${SECRET_NAS_SERVER}
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-consume-pvc
spec:
  storageClassName: paperless-consume-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ai-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-standard
  resources:
    requests:
      storage: 5Gi
