---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plugin-barman-cloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: plugin-barman-cloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY_ID: "{{ .S3_KEY_ID}}"
        SECRET_ACCESS_KEY: "{{ .S3_KEY_SECRET }}"
  dataFrom:
    - extract:
        key: cloudflare
