---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immich-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_USERNAME: "{{ .IMMICH_POSTGRESQL_USERNAME }}"
        DB_PASSWORD: "{{ .IMMICH_POSTGRESQL_PASSWORD }}"
        JWT_SECRET: "{{ .IMMICH_JWT_SECRET }}"
        IMMICH_REDIS_PASSWORD: "${DRAGONFLY_PASSWORD}"
  dataFrom:
    - extract:
        key: immich
