---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      annotations:
        reloader.stakater.com/auto: "true"
        secret.reloader.stakater.com/reload: immich-secret
      securityContext:
        runAsUser: 3000
        runAsGroup: 3000
        fsGroup: 3000
    controllers:
      main:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          immich-server:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.142.0
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 3072Mi
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            env:
              - name: DB_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: cnpg-immich-superuser
                    key: username
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cnpg-immich-superuser
                    key: password
              - name: REDIS_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: immich-secret
                    key: IMMICH_REDIS_PASSWORD
            envFrom:
              - configMapRef:
                  name: immich-immich-config
          immich-machine-learning:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.142.1
            resources:
              requests:
                cpu: 15m
                memory: 250Mi
              limits:
                memory: 4000Mi
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            env:
              - name: DB_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: cnpg-immich-superuser
                    key: username
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cnpg-immich-superuser
                    key: password
              - name: REDIS_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: immich-secret
                    key: IMMICH_REDIS_PASSWORD
            envFrom:
              - configMapRef:
                  name: immich-immich-config
    service:
      immich-server:
        controller: main
        ports:
          http:
            port: 2283
      immich-machine-learning:
        controller: main
        ports:
          http:
            port: 3003
    route:
      immich-server:
        hostnames:
          - media.${SECRET_DOMAIN}
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: immich-immich-server
                port: 2283
    configMaps:
      immich-config:
        enabled: true
        data:
          TZ: ${TIMEZONE}
          IMMICH_CONFIG_FILE: &configLocation /usr/src/app/immich.json
          IMMICH_MEDIA_LOCATION: &mediaLocation /usr/src/app/upload
          IMMICH_ENV: production
          REDIS_HOSTNAME: "dragonfly.database.svc.cluster.local"
          REDIS_PORT: "6379"
          REDIS_DBINDEX: "1"
          DB_HOSTNAME: "cnpg-immich-rw.default.svc.cluster.local"
          DB_PORT: "5432"
          DB_DATABASE_NAME: "immichdb"
          DB_VECTOR_EXTENSION: "vectorchord"
      immich-json:
        enabled: true
        data:
          immich.json: |
            {
              "ffmpeg": {
                "crf": 23,
                "threads": 0,
                "preset": "ultrafast",
                "targetVideoCodec": "h264",
                "acceptedVideoCodecs": ["h264"],
                "targetAudioCodec": "aac",
                "acceptedAudioCodecs": ["aac", "mp3", "libopus", "pcm_s16le"],
                "acceptedContainers": ["mov", "ogg", "webm"],
                "targetResolution": "720",
                "maxBitrate": "0",
                "bframes": -1,
                "refs": 0,
                "gopSize": 0,
                "temporalAQ": false,
                "cqMode": "auto",
                "twoPass": false,
                "preferredHwDevice": "auto",
                "transcode": "required",
                "tonemap": "hable",
                "accel": "disabled",
                "accelDecode": false
              },
              "backup": {
                "database": {
                  "enabled": true,
                  "cronExpression": "0 02 * * *",
                  "keepLastAmount": 14
                }
              },
              "job": {
                "backgroundTask": {
                  "concurrency": 5
                },
                "smartSearch": {
                  "concurrency": 2
                },
                "metadataExtraction": {
                  "concurrency": 5
                },
                "faceDetection": {
                  "concurrency": 2
                },
                "search": {
                  "concurrency": 5
                },
                "sidecar": {
                  "concurrency": 5
                },
                "library": {
                  "concurrency": 5
                },
                "migration": {
                  "concurrency": 5
                },
                "thumbnailGeneration": {
                  "concurrency": 3
                },
                "videoConversion": {
                  "concurrency": 1
                },
                "notifications": {
                  "concurrency": 5
                }
              },
              "logging": {
                "enabled": true,
                "level": "log"
              },
              "machineLearning": {
                "enabled": true,
                "urls": ["http://immich-immich-machine-learning.default.svc.cluster.local:3003"],
                "clip": {
                  "enabled": true,
                  "modelName": "ViT-B-32__openai"
                },
                "duplicateDetection": {
                  "enabled": true,
                  "maxDistance": 0.01
                },
                "facialRecognition": {
                  "enabled": true,
                  "modelName": "buffalo_l",
                  "minScore": 0.7,
                  "maxDistance": 0.5,
                  "minFaces": 3
                }
              },
              "map": {
                "enabled": true,
                "lightStyle": "https://tiles.immich.cloud/v1/style/light.json",
                "darkStyle": "https://tiles.immich.cloud/v1/style/dark.json"
              },
              "reverseGeocoding": {
                "enabled": true
              },
              "metadata": {
                "faces": {
                  "import": true
                }
              },
              "oauth": {
                "autoLaunch": true,
                "autoRegister": true,
                "buttonText": "Login with Authentik",
                "clientId": "${IMMICH_OPENID_CLIENT_ID}",
                "clientSecret": "${IMMICH_OPENID_CLIENT_SECRET}",
                "defaultStorageQuota": 10,
                "enabled": true,
                "issuerUrl": "https://id.${SECRET_DOMAIN}/application/o/immich/",
                "mobileOverrideEnabled": false,
                "mobileRedirectUri": "",
                "scope": "openid email profile",
                "signingAlgorithm": "RS256",
                "profileSigningAlgorithm": "none",
                "storageLabelClaim": "preferred_username",
                "storageQuotaClaim": "quota"
              },
              "passwordLogin": {
                "enabled": false
              },
              "storageTemplate": {
                "enabled": false,
                "hashVerificationEnabled": true
              },
              "image": {
                "thumbnail": {
                  "format": "webp",
                  "size": 250,
                  "quality": 80
                },
                "preview": {
                  "format": "jpeg",
                  "size": 1440,
                  "quality": 80
                },
                "colorspace": "p3",
                "extractEmbedded": false
              },
              "newVersionCheck": {
                "enabled": true
              },
              "trash": {
                "enabled": true,
                "days": 30
              },
              "theme": {
                "customCss": ""
              },
              "library": {
                "scan": {
                  "enabled": true,
                  "cronExpression": "0 0 * * *"
                },
                "watch": {
                  "enabled": false
                }
              },
              "server": {
                "externalDomain": "https://media.${SECRET_DOMAIN}",
                "loginPageMessage": ""
              },
              "notifications": {
                "smtp": {
                  "enabled": true,
                  "from": "admin@${SECRET_DOMAIN}",
                  "replyTo": "",
                  "transport": {
                    "ignoreCert": true,
                    "host": "${SECRET_MAIL_SERVER}",
                    "port": 25,
                    "username": "",
                    "password": ""
                  }
                }
              },
              "user": {
                "deleteDelay": 7
              }
            }
    persistence:
      data:
        enabled: true
        existingClaim: immich-pvc
        globalMounts:
          - path: *mediaLocation
      cache:
        enabled: true
        type: emptyDir
      immich-json:
        type: configMap
        name: immich-immich-json
        advancedMounts:
          main:
            immich-server:
              - path: *configLocation
                subPath: immich.json
                readOnly: true
