---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cnpg-authentik-pv
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cnpg-authentik-nfs
  mountOptions:
    - hard
    - rw
    - nfsvers=4.2
  nfs:
    path: /mnt/hdd/k8s/pgs/atk
    server: ${SECRET_NAS_SERVER}
    readOnly: false

