apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    TIMEZONE: ENC[AES256_GCM,data:DkKoZYc82M8tQf4gYA==,iv:lLwvaZ3VERblh+taXVsp833BEZjsvt+xVPWnfUgQoP4=,tag:ErnNPhjzmhnjMTwJekJI2w==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:lzmUxPRdOuxOuw==,iv:vsxZj95vmMg9uMLYKMXiO7U1QL7SRtIHVLy8jGe4uGY=,tag:E1tSsjfH59AwOsN5xhKFhA==,type:str]
    SECRET_NAS_SERVER: ENC[AES256_GCM,data:o9Gk6xjRM6FtSRyPdf4=,iv:2n/ig49p0gyUgP8LzCOQaoDTsHUEvGALKD7xpRyLXo8=,tag:qKLbeP7qKwX+mOFsandJVQ==,type:str]
    SECRET_MAIL_SERVER: ENC[AES256_GCM,data:CucduBl6f3vMcrHF,iv:Al/bsH4r+p51hRdZ6Q9L7p1vZHWAiP2srjTwa+xd+lQ=,tag:j96beD+o10RQGgz6xtrpVg==,type:str]
    SECRET_S3_URL: ENC[AES256_GCM,data:ucdfj8vz3RiRtVfNAmdET4YVBWdh9FcmeREuNgtgLxUV6sSIu0wNUcFvxHPufwcjU3k2vidhpznAr1IF10kYJ9agVTLV,iv:bpJAw16pLKD1WsmQBQPedN5Gu9EXU7l7/2XI+RA5egU=,tag:Yho/POCRKLqLGZUE8EQunQ==,type:str]
    DRAGONFLY_PASSWORD: ENC[AES256_GCM,data:veHZhC7SgZFb0SqM05Nmc0ygS5bAQz7QkJa7X3orkWxPrrajNdFIg2GC2K/fh7X0MtA=,iv:hKajVYq90Etje61GemeqaE9QOsLmjVF9hmmZBC81k2c=,tag:va3kdp1JPTwF3LzcYFS3TA==,type:str]
    PAPERLESS_OPENID_CLIENT_ID: ENC[AES256_GCM,data:AVh5FrdHRvWDFOpUWJCniOwEMqatjN/8OhdpDOBO8IzQN6dIBbvXZQ==,iv:e7F7B7tOrT3UoZVU/R1ln3jKN++L+vyRnMQP7y5yxaY=,tag:oBZlYT5lMJpW9NXPY56now==,type:str]
    PAPERLESS_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:pGa2MeTXi3sCmYYOJM1t2BKOVCbVW5mR5D2GWaT81bwscX+fsLqGJZqXYccZgcxcGY6v+K14gElVtAwWfphSgEWamF/c6nKS8oq0EmaMgNJYDfcDXBKD1PEavAWhLlYCbusMifxWQcm1trX1YFbKdL6/LtNfQm6aV8oC5X6N5IM=,iv:NsurcqAVqLydlmsZcLSabJAR4CG+W8Vmj1vSQCi4Nto=,tag:o64dPby0vyejaRY3U+U9Kw==,type:str]
    NEXTCLOUD_OPENID_CLIENT_ID: ENC[AES256_GCM,data:9h7Y/syc30pR9Xp83aSUAP7qp0hJ6nodb74p48vQNpMQ00n/TX1/oA==,iv:IFMvwT5fMFBgpghwAHVLCl3Qz1DDDUp6AVEsZBuEaYg=,tag:9A2ntcUF/RCSQyUSGSN1aA==,type:str]
    NEXTCLOUD_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:eA+fBnIOvJAc0MPtrCgmpkAnsrL4epa5UPbDE0EWUZU0Qt0TiDPP/dDZNP7BkIRO51KdyETBFiS/MrFNv4Y9/Kq1/pV9/xXeueMP1Iq9ewjvCNw5BxjfVI+SkAeIwKifVgcEJI3nhNGr57Y7DBI8mFjmHTVfR8Uv+0NEudsChfM=,iv:R+Ta3+Qe2GOf2lgSTw7VL7uIBMTs5DacM3zOzM6JokA=,tag:shMO2uLPEeNhF0LvdhcdVw==,type:str]
    IMMICH_OPENID_CLIENT_ID: ENC[AES256_GCM,data:tsRBUhb3VbswshnDfeFx5hsmnVlIwSOuVMbOhd0/YyE4eTjMrbzBNQ==,iv:zdpjV4qi1ZXHUKn2qkkWJX1qRJ3orP89dADuJo8/GD0=,tag:eadV0baGN/IaB2VdfERH/A==,type:str]
    IMMICH_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:DSIEaVznNBfVNFRBXCRplXVrXnvmi6yRvfIw9uSXnalwrYk9qxEwPIOK/qkhAeqrWKEX+RytVskOEZlCSiNi0Bytse+h8gEl/LtoBdgRibpqAHObMMB1p/iLG7MK8mJvXum6kfL2NTehEtIQuhLylsJrgehcZxthcWNo+dcXipM=,iv:hgcEf/7QzjJuWHELgezlqNZ6hJng6DKQae+1VBRGkkI=,tag:ntX3Lk9BpF8YtE1/MVqmbQ==,type:str]
sops:
    age:
        - recipient: age1xpc9arrkc8a3hdgaepzaaw0zm3pp4mhatkjk0k83wq00klzyvs4ssqt5mp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWHFXY2NrMjdLK3VhdGpj
            ZTFzOWJtWXowLzlmakRLWlE1OFFSY2E3U3ljCjZHR3VnVjhPTkp4Wk9tRkIzVXFj
            ZVpEc056dmdkaWhVVCsvNGlZblhjcjgKLS0tIHFtK3lTL3hmQ1l3NVFlQ0MwTU9S
            UzFrOW9pZUxPS05mSm5OUXIrSWZCQnMKzymWIFF/WucacOHrPmMeM9V7rZ/CQKHC
            4b4r1qn7zwh6qRysTfk1i/pftGIanRPgAYagmn46yUtfrXVeNVqE4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T16:34:48Z"
    mac: ENC[AES256_GCM,data:HbFcofONo5pvHCVnae4PCAZHbcPwYypTJebVbKGCi+++jp/BlivTH2sn5DtdgmPsEk0nJBq0Cmw57UBVSB+htkIcYtKgYqaQ0vivRiN72QGHF55Kh8D6bb50QtKUl9D3COgeT5Vk2Q+/TMx0vyU4txuf+HcbgEQpPEnRgvHK6x4=,iv:8teJL4j1QdLjbD0jjUhI4UvAXkuIwKq8VNdt8U9p870=,tag:VGLgvrAs/778jB4E4aUC7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
